apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: pod-alerts
spec:
  groups:
  - name: pod.rules
    rules:
    - alert: PodRestartHigh
      expr: increase(kube_pod_container_status_restarts_total[5m]) > 2
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "Pod restarting frequently"
